# docker-compose.yml
version: '3.8'

services:
  flask-service:
    build:
      context: ./flask-app
    ports:
      - "3001:5000"

  node-service:
    build:
      context: ./node-app
    ports:
      - "3000:3000"