version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recipedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5050
    volumes:
      - .:/app
    ports:
      - "5050:5050"
    depends_on:
      - db

volumes:
  db_data:
