version: '3.8'

services:
  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      